name: Release
on:
  push:
    branches: [main]

permissions:
  contents:      read  # Clone repo
  id-token:      write # Depot OIDC

jobs:
  verify:
    uses: ./.github/workflows/verify.yml
    secrets: inherit
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: false

  build:
    env:
      DOCKER_IMAGE: "526236635984.dkr.ecr.us-east-1.amazonaws.com/warpcast/scores-frame:${{ github.sha }}"
    timeout-minutes: 15
    runs-on: depot-ubuntu-latest-arm
    outputs:
      docker-image: ${{ env.DOCKER_IMAGE }}
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::526236635984:role/github-actions-workflow-warpcast-scores-frame
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - uses: ./.github/actions/build
        with:
          dockerhub-user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          dockerfile: ./Dockerfile
          depot: true
          depot-project-id: ${{ secrets.DEPOT_PROJECT_ID }}
          image-tag: ${{ env.DOCKER_IMAGE }}
          context: .
          platforms: 'linux/arm64'
          push: true

  deploy:
    concurrency:
      group: deploy-scores-frame
      cancel-in-progress: false
    needs: build
    timeout-minutes: 10
    runs-on: ['runs-on=${{ github.run_id }}', 'runner=1cpu-linux-arm64']
    steps:
      - uses: warpcast/remote-exec@v1.2.5
        with:
          git-repo: ${{ github.repository }}
          git-ref: ${{ github.sha }}
          docker-image: ${{ needs.build.outputs.docker-image }}
          command: deploy
          project: scores-frame
          ssh-key: ${{ secrets.STACK_DEPLOY_SSH_PRIVATE_KEY }}
